### ISSUE TITLE
Aplicar el patrón de Diseño MEMENTO Y SINGLETON

### ISSUE THREAD

**Issue by Luismillones20** [Luismillones20/nosdespedimosdeprogra#3]
Aplicar un while ya que no hay memoria de lo que se hace una vez corre el programa. Y no se puede volver a un estado anterior.
Es decir: 
Cuando se ejecuta, solo puedo ver las siguientes 5 peliculas, pero si es que he visto 10 paginas de peliculas (con paginas me refiero a que se ha puesto "ver siguientes peliculas" 10 veces) debería poder volver a las primeras 5 películas que vi al principio
Igualmente debe aplicarse el patrón de Singleton

**Comment by Davidht77** [comment]
Falta arreglar el memento
