### ISSUE TITLE
Algoritmo de LIKES, VER MAS TARDE y RECOMENDACIÓN DE PELÍCULAS

### ISSUE THREAD

**Issue by Luismillones20** [Luismillones20/nosdespedimosdeprogra#5]
Deberiamos ser capaces de poder dar like y ver más tarde a una pelicula y con base a ello se debería recomendarnos una vez volvamos al menu nuevamente

**Comment by Davidht77** [comment]
Falta arreglar el ordenamiento al seleccionar un indice de las sinopsis
